version: "3"
services:
  pim.huis-en-wonen.localhost:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    volumes:
      - .:/var/www/html
    restart: "no"
    depends_on:
      - mysql.pim.huis-en-wonen.localhost

  mysql.pim.huis-en-wonen.localhost:
    image: mysql:8
    volumes:
      - unopim-mysql-disk:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unopim

  queue.pim.huis-en-wonen.localhost:
    build:
      context: .
      dockerfile: dockerfiles/q.Dockerfile
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql.pim.huis-en-wonen.localhost

# On-disk storage of DB data, when containers are stopped
volumes:
  unopim-mysql-disk: { }
