<?php

namespace App\Services\ProductImageEditor;

use App\Models\AssetLogoVariant;
use App\Services\ProductImageEditor\Concerns\HandlesDamValues;
use Illuminate\Support\Facades\Storage;
use Webkul\DAM\Models\Asset;
use Webkul\DAM\Repositories\AssetResourceMappingRepository;
use Webkul\Product\Models\Product;

/**
 * Applies the HW logo to every image in the product gallery (the configured
 * primary asset attribute), not just the main one.
 *
 * An image is never stamped twice. An asset is recognised as already carrying
 * the logo when it is:
 *   - a variant recorded in asset_logo_variants (stamped by this service),
 *   - the composite generated by the primary image editor for this product,
 *   - named with the "-hw-" suffix EditedAssetWriter gives every logo variant,
 *   - visually detected to already show the logo in its bottom-left corner
 *     (manual stamps from before this bookkeeping existed); such assets are
 *     recorded in asset_logo_variants as their own variant so the pixel check
 *     runs at most once per asset.
 *
 * When a source asset was already stamped for another product, its existing
 * variant is reused instead of generating a duplicate. Source assets are left
 * untouched in the DAM library; the gallery is rewired to the variants.
 */
class GalleryLogoService
{
    use HandlesDamValues;

    public function __construct(
        private ImageCompositor $compositor,
        private EditedAssetWriter $writer,
        private HwIconResolver $iconResolver,
        private LogoPresenceDetector $logoDetector,
        private AssetResourceMappingRepository $assetResourceMappingRepository,
    ) {}

    /**
     * Stamp the HW logo on every gallery image that does not have it yet.
     * "skipped" means already stamped or unusable; keys are source asset ids.
     *
     * @return array{stamped: array<int, int>, reused: array<int, int>, skipped: array<int, int>}
     */
    public function apply(Product $product, bool $dryRun = false): array
    {
        $summary = ['stamped' => [], 'reused' => [], 'skipped' => []];

        if (! config('product_image_editor.enabled')) {
            return $summary;
        }

        $config = config('product_image_editor');
        $attribute = $config['primary_attribute'];

        $values = $this->normalizeValues($product->values);
        $ids = $this->assetIdList($values['common'][$attribute] ?? null);

        if ($ids === []) {
            return $summary;
        }

        $iconContents = $this->iconResolver->contents();

        if (! $iconContents) {
            return $summary;
        }

        $variantsBySource = AssetLogoVariant::query()
            ->whereIn('source_asset_id', $ids)
            ->pluck('variant_asset_id', 'source_asset_id');

        $knownVariantIds = AssetLogoVariant::query()
            ->whereIn('variant_asset_id', $ids)
            ->pluck('variant_asset_id');

        $editorAssetId = (int) ($product->additional['primary_image_editor']['edited_asset_id'] ?? 0);

        $disk = $config['asset_disk'];
        $quality = (int) ($config['quality'] ?? 90);

        $newIds = [];
        $changed = false;

        foreach ($ids as $id) {
            $asset = Asset::find($id);

            if (! $asset || $this->isAlreadyStamped($asset, $editorAssetId, $knownVariantIds->all())) {
                $newIds[] = $id;
                $summary['skipped'][] = $id;

                continue;
            }

            $variantId = (int) ($variantsBySource[$id] ?? 0);

            if ($variantId && Asset::query()->whereKey($variantId)->exists()) {
                $newIds[] = $variantId;
                $summary['reused'][] = $id;
                $changed = true;

                continue;
            }

            if (! Storage::disk($disk)->exists($asset->path)) {
                $newIds[] = $id;
                $summary['skipped'][] = $id;

                continue;
            }

            $contents = Storage::disk($disk)->get($asset->path);

            if ($this->logoDetector->hasLogo($contents, $iconContents)) {
                if (! $dryRun) {
                    AssetLogoVariant::updateOrCreate(
                        ['source_asset_id' => $id],
                        ['variant_asset_id' => $id],
                    );
                }

                $newIds[] = $id;
                $summary['skipped'][] = $id;

                continue;
            }

            if ($dryRun) {
                $newIds[] = $id;
                $summary['stamped'][] = $id;

                continue;
            }

            $stamped = $this->compositor->stampIcon($contents, $iconContents);

            $variant = $this->writer->store($asset, (string) $stamped->toJpeg($quality), 'hw');

            AssetLogoVariant::updateOrCreate(
                ['source_asset_id' => $id],
                ['variant_asset_id' => $variant->id],
            );

            $newIds[] = (int) $variant->id;
            $summary['stamped'][] = $id;
            $changed = true;
        }

        if ($dryRun || ! $changed) {
            return $summary;
        }

        $newIds = array_values(array_unique($newIds));

        $values['common'][$attribute] = implode(',', $newIds);
        $product->values = $values;
        $product->saveQuietly();

        $this->assetResourceMappingRepository->createProductAssetMappings($newIds, $product->id, $attribute);

        return $summary;
    }

    /**
     * @param  array<int, int>  $knownVariantIds
     */
    private function isAlreadyStamped(Asset $asset, int $editorAssetId, array $knownVariantIds): bool
    {
        if ((int) $asset->id === $editorAssetId) {
            return true;
        }

        if (in_array((int) $asset->id, array_map('intval', $knownVariantIds), true)) {
            return true;
        }

        return (bool) preg_match('/-hw-[a-z0-9]{6}\.jpe?g$/i', (string) $asset->file_name);
    }
}
