<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('demunk_product_links', function (Blueprint $table) {
            $table->id();

            // The PIM design+colour product (configurable, e.g. DMC0014 "Diamante 01").
            $table->unsignedInteger('product_id');

            // The matched De Munk article coordinates. Null means "no De Munk
            // source" — a user-suppressed product that should not be re-matched.
            $table->string('demunk_collectie')->nullable();
            $table->string('demunk_kwaliteit')->nullable();
            $table->string('demunk_kleur')->nullable();
            $table->string('demunk_vorm')->nullable();

            // Fuzzy/deterministic score (0-100) the auto-matcher assigned.
            $table->unsignedTinyInteger('match_score')->nullable();

            // 'auto' links are (re)generated by the matcher; 'manual' links were
            // set by a user. Locked links are never touched by the auto-matcher.
            $table->enum('source', ['auto', 'manual'])->default('auto');
            $table->boolean('locked')->default(false);

            $table->timestamps();

            $table->unique('product_id');
            $table->index(['demunk_collectie', 'demunk_kwaliteit', 'demunk_kleur'], 'demunk_links_article_index');

            $table->foreign('product_id')->references('id')->on('products')->cascadeOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('demunk_product_links');
    }
};
